const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),{JSDOM}=require(process.cwd()+'/node_modules/jsdom');
const dom=new JSDOM(fs.readFileSync('web/index.html','utf8'),{url:'https://test.local/',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;w.structuredClone=structuredClone;w.alert=m=>{throw Error(m)};let accepted=true,prompts=[];w.confirm=m=>{prompts.push(m);return accepted};w.HTMLElement.prototype.scrollIntoView=function(){};w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};w.scheduleSync=()=>{};w.scrollTo=()=>{};
for(const script of w.document.querySelectorAll('script')){const src=script.getAttribute('src');if(src&&(/cloud|firebase|https:/.test(src)))continue;try{vm.runInContext(src?fs.readFileSync('web/'+src,'utf8'):script.textContent,dom.getInternalVMContext())}catch(e){console.error('script',src);throw e}}
w.document.dispatchEvent(new w.Event('DOMContentLoaded'));const run=s=>vm.runInContext(s,dom.getInternalVMContext());
run(`CATPV.ensure(data).products.push({id:'p1',name:'Pantalón',category:'Ropa',kind:'product',price:2500,vat:21,tracked:true,stock:10,archived:false},{id:'s1',name:'Manicura',category:'Manos',kind:'service',price:1000,vat:21,tracked:false,stock:0,duration:30,archived:false});CATPVUI.tab('catalogue')`);
const sections=w.document.querySelectorAll('#tpvProducts section');assert.equal(sections.length,2);assert.match(sections[0].textContent,/Pantalón/);assert(!sections[0].textContent.includes('Manicura'));assert.match(sections[1].textContent,/Manicura/);
run(`CATPVUI.newProduct('product')`);assert.equal(w.document.getElementById('tpvKind').value,'product');
run(`CATPV.sell(data,{cart:[{productId:'p1',qty:1}],customerId:'',date:'2026-10-09',method:'cash',discountBps:0});CATPVUI.add('s1')`);
accepted=false;run('CATPVUI.clearCatalogue()');assert.equal(run('data.tpv.products.length'),2);accepted=true;run('CATPVUI.clearCatalogue()');assert.equal(w.document.querySelectorAll('#tpvProducts .staffRow').length,0);assert.equal(run('data.tpv.products.length'),1);assert.equal(run('data.tpv.sales.length'),1);assert.equal(run('data.tpv.products[0].catalogueDeleted'),true);assert.match(w.document.getElementById('tpvCart').textContent,/vacío/);
run(`CATPVUI.archiveProduct('p1');CAStore.validate(data);CATPV.refund(data,data.tpv.sales[0].id,'2026-10-09','cash');CAStore.validate(data)`);assert.equal(run('data.tpv.products[0].stock'),10);assert.equal(run('data.tpv.products[0].archived'),true);
run('CAStore.validate(JSON.parse(JSON.stringify(data)))');
console.log('OK catálogo separado, cancelar/confirmar vaciado, carrito, historial, devolución y copia');dom.window.close();
