const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert/strict'),{chromium}=require('playwright');
const server=http.createServer((req,res)=>{try{const p=new URL(req.url,'http://localhost').pathname;res.setHeader('Content-Type',p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(path.join(__dirname,'../web',p==='/'?'index.html':p)))}catch{res.statusCode=404;res.end()}});
(async()=>{await new Promise(r=>server.listen(8767,'127.0.0.1',r));const b=await chromium.launch({headless:true});const page=await b.newPage({serviceWorkers:'block',viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.route('**/cloud.js',route=>route.fulfill({contentType:'text/javascript',body:'window.scheduleSync=function(){};'}));await page.goto('http://127.0.0.1:8767');await page.waitForFunction(()=>window.CAEmployees);
await page.locator('.homeMenu').getByRole('button',{name:'Mi cuenta',exact:true}).click();assert(await page.locator('#account').isVisible());assert(await page.locator('.account-panel').isVisible());assert.equal(await page.locator('#settings').isVisible(),false);await page.locator('#account .returnHome').click();await page.locator('.homeMenu').getByRole('button',{name:'Ajustes',exact:true}).click();assert(await page.locator('#settings').isVisible());assert.equal(await page.locator('.account-panel').isVisible(),false);const helpTopics=await page.locator('#appHelp > details > summary').allTextContents();for(const topic of ['Empleados: dar de alta y archivar','Sueldo y Seguridad Social: registrar costes','Vacaciones: cupos, fechas y días','Agenda de citas · Pro'])assert(helpTopics.includes(topic),'Falta ayuda: '+topic);await page.evaluate(()=>show('home'));

await page.evaluate(()=>{data.movements=[];data.employees=[];data.payrolls=[];data.vacations=[];save()});assert.equal(await page.locator('.nav').isVisible(),false);assert(await page.locator('.fab').isVisible());await page.evaluate(()=>scrollTo(0,9999));assert(await page.locator('.fab').isVisible());assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.evaluate(()=>show('employees'));
await page.locator('#staffName').fill('Ana <prueba>');await page.locator('#staffAllowance').fill('22');await page.locator('#staffYear').fill('2026');await page.evaluate(()=>CAEmployees.saveEmployee());await page.locator('#payDate').fill('2026-10-01');await page.locator('#paySalary').fill('1500');await page.locator('#paySocial').fill('450');await page.locator('#payOther').fill('50');await page.evaluate(()=>CAEmployees.addCost());assert.equal(await page.evaluate(()=>data.movements.length),1);assert.equal(await page.evaluate(()=>monthlyBenefit(2026,10).gas),2000);assert.equal(await page.evaluate(()=>CAProReports.totals(data.movements,2026,10).expense),2000);await page.locator('#vacStart').fill('2026-10-12');await page.locator('#vacEnd').fill('2026-10-16');await page.locator('#vacDays').fill('5');await page.evaluate(()=>CAEmployees.addVacation());assert.equal(await page.evaluate(()=>data.vacations.length),1);assert.equal(await page.evaluate(()=>data.movements.length),1);
await page.reload();await page.waitForFunction(()=>window.CAEmployees);assert.equal(await page.evaluate(()=>data.payrolls.length),1);assert.equal(await page.evaluate(()=>data.vacations.length),1);await page.evaluate(()=>{const copy=CAStore.validate(JSON.parse(JSON.stringify(data)));if(copy.payrolls.length!==1)throw Error('backup');CAEmployees.removeCost(data.payrolls[0].id)});assert.equal(await page.evaluate(()=>data.movements.length),0);
await page.evaluate(()=>{data.movements.push({id:456,type:'Gasto',date:'2026-10-01',concept:'Nómina previa',total:2000,vat:0});save()});await page.evaluate(()=>show('employees'));await page.locator('#payDate').fill('2026-10-01');await page.locator('#paySalary').fill('1500');await page.locator('#paySocial').fill('450');await page.locator('#payOther').fill('50');await page.locator('#payLink').selectOption('456');await page.evaluate(()=>CAEmployees.addCost());assert.equal(await page.evaluate(()=>data.movements.length),1);await page.evaluate(()=>CAEmployees.removeCost(data.payrolls[0].id));assert.equal(await page.evaluate(()=>data.movements.length),1);assert.equal(await page.evaluate(()=>data.movements[0].payrollId),undefined);
await page.evaluate(()=>show('home'));await page.screenshot({path:path.join(__dirname,'../delivery/inicio.png'),fullPage:true});await page.evaluate(()=>show('employees'));await page.screenshot({path:path.join(__dirname,'../delivery/empleados.png'),fullPage:true});assert.deepEqual(errors,[]);await b.close();server.close();console.log('OK navigation, mobile overflow, costs once, linked expenses, vacations, persistence and backup');})().catch(e=>{console.error(e);server.close();process.exit(1)});
