const assert=require('assert/strict'),create=require('./helpers/app-dom.cjs');
(async()=>{const a=create(),{run,w,el,alerts}=a;
run(`data.movements.push({id:1,date:'2026-10-09',type:'Ingreso',concept:'Original',total:121,vat:21,paymentMethod:'cash',withholding:0});document.getElementById('year').value='2026';document.getElementById('reportMonth').value='10';render()`);assert.equal(run('monthlyIncomeRows()[0].total'),121);run(`data.nonworking.push('2026-10-09');render()`);assert.equal(run('monthlyIncomeRows()[0].total'),121);assert.equal(run('reportedIncome(2026,10)[0].total'),121);assert.equal(run('monthlyBenefit(2026,10).inc'),121);
el('irpf').value='0';run('saveSettings()');assert.equal(run('data.settings.irpf'),0);assert.equal(run('monthlyBenefit(2026,10).irpf'),0);run('renderQuarters()');assert(!el('quarters').textContent.includes('20,00'));
run('editMovement(1)');el('concept').value='Corregido <img src=x onerror=alert(1)>';el('total').value='242';a.accept(false);run('addMovement()');assert.equal(run('data.movements[0].total'),121);a.accept(true);run('addMovement()');assert.equal(run('data.movements.length'),1);assert.equal(run('data.movements[0].total'),242);assert.equal(run('CAStore.read(null).data.movements[0].total'),242);assert.equal(w.document.querySelector('#recent img'),null);
// Closed dates do not prevent recording a real income or receipt.
run('openAdd()');el('date').value='2026-10-09';el('total').value='10';el('paymentMethod').value='card';el('concept').value='Ingreso en día cerrado';run('addMovement()');assert.equal(run('data.movements.length'),2);
// Stock entry, low stock threshold, filters and archived visibility.
run(`show('tpv');CATPVUI.tab('catalogue');CATPVUI.newProduct('product')`);el('tpvProductName').value='Champú';el('tpvProductCategory').value='Cabello';el('tpvPrice').value='10';el('tpvTracked').checked=true;el('tpvStock').value='2';el('tpvMinStock').value='3';run('CATPVUI.saveProduct()');const pid=run('data.tpv.products[0].id');assert.match(el('tpvProducts').textContent,/Stock bajo/);assert.equal(run('data.tpv.stockHistory[0].after'),2);run(`CATPVUI.openStock('${pid}')`);el('stockQty').value='5';el('stockReason').value='Compra';run('CATPVUI.saveStock()');assert.equal(run('data.tpv.products[0].stock'),7);assert.match(el('stockHistory').textContent,/Compra/);el('stockMode').value='set';el('stockQty').value='4';el('stockReason').value='Recuento';run('CATPVUI.saveStock()');assert.equal(run('data.tpv.products[0].stock'),4);el('stockDialog').close();el('tpvManageSearch').value='CHAMPU';run('CATPVUI.draw()');assert.match(el('tpvProducts').textContent,/Champú/);el('tpvManageSearch').value='No existe';run('CATPVUI.draw()');assert(!el('tpvProducts').textContent.includes('Champú'));el('tpvManageSearch').value='';run(`CATPVUI.archiveProduct('${pid}')`);assert(!el('tpvProducts').textContent.includes('Champú'));el('tpvShowArchived').checked=true;run('CATPVUI.draw()');assert.match(el('tpvProducts').textContent,/Archivado/);run(`CATPVUI.archiveProduct('${pid}')`);
// A damaged product returns money but not stock, even after catalogue cleanup.
run(`CATPV.sell(data,{cart:[{productId:'${pid}',qty:2}],date:'2026-10-09',method:'cash',discountBps:1000});CATPVUI.draw();CATPVUI.refundDialog(data.tpv.sales[0].id)`);w.document.querySelector('[data-return-index]').value='1';w.document.querySelector('[data-restock-index]').checked=false;el('tpvPaymentDate').value='2026-10-09';el('tpvPaymentMethod').value='cash';run('CATPVUI.confirmPayment()');assert.equal(run('data.tpv.products[0].stock'),2);assert.equal(run('data.tpv.sales[0].returns[0].lines[0].restock'),false);run('CAStore.validate(data)');
// Manual service appointment -> price -> cart -> one paid sale; never appears in catalogue.
run(`data.nonworking=[];CAAgenda.save(data,{customerId:'',productIds:[],serviceName:'Manicura especial',date:'2026-10-10',time:'09:00',duration:30,status:'pending',notes:''});CATPVUI.startAppointment(data.tpv.appointments[0].id)`);assert.equal(el('manualSaleName').value,'Manicura especial');assert.equal(el('manualSaleDialog').open,true);el('manualSalePrice').value='18,50';run('CATPVUI.useManualAppointment()');assert.match(el('tpvCart').textContent,/Manicura especial/);el('tpvMethod').value='cash';run('CATPVUI.checkout()');assert.equal(run('data.tpv.sales[1].total'),1850);assert.equal(run('data.tpv.appointments[0].saleId'),run('data.tpv.sales[1].id'));run('CATPVUI.tab("catalogue")');assert(!el('tpvProducts').textContent.includes('Manicura especial'));run('CAStore.validate(data)');el('tpvDetailDialog').close();
// Weekly recurrence is atomic on closed dates; success spans month/year boundaries.
run(`show('agenda');CAAgendaUI.reset();document.getElementById('agendaDate').value='2026-12-28';document.getElementById('agendaRepeat').value='weekly';document.getElementById('agendaRepeatCount').value='3';data.nonworking=['2027-01-04']`);const before=run('data.tpv.appointments.length');run('CAAgendaUI.save()');assert.equal(run('data.tpv.appointments.length'),before);assert.match(alerts.at(-1),/04\/01\/2027/);run('data.nonworking=[];CAAgendaUI.save()');assert.equal(run('data.tpv.appointments.length'),before+3);assert.equal(run('data.tpv.appointments.at(-1).date'),'2027-01-11');assert.equal(new Set(run('data.tpv.appointments.slice(-3).map(a=>a.seriesId)')).size,1);run('CAAgendaUI.setStatus(data.tpv.appointments.at(-1).id,"completed")');assert.equal(run('data.tpv.appointments.at(-1).status'),'completed');assert.match(el('agendaDaily').textContent,/Próximas citas/);assert.match(el('cash').textContent,/No es el saldo disponible/);assert.match(el('backupStatus').textContent,/No hay fecha/);
// Backup metadata only confirms native success; a cancelled save is not recorded.
w.AndroidFiles={saveFile(){}};w.downloadFileCompat=async()=>{};await run('exportData()');assert.match(el('backupStatus').textContent,/Elige dónde/);run('CABackups.nativeSaved(false)');assert.match(el('backupStatus').textContent,/No hay fecha/);await run('exportData()');run('CABackups.nativeSaved(true)');assert.match(el('backupStatus').textContent,/Última copia guardada/);const raw=run('JSON.stringify(data)'),imported=JSON.parse(raw);imported.settings.owner='Restaurado';const target={files:[new w.File([JSON.stringify(imported)],'copia.json',{type:'application/json'})],value:'copia'};a.accept(false);w.importData({target});await new Promise(r=>setTimeout(r,30));assert.notEqual(run('data.settings.owner'),'Restaurado');assert.match(a.prompts.at(-1),/citas/);assert.equal(target.value,'');a.accept(true);target.value='copia';w.importData({target});await new Promise(r=>setTimeout(r,30));assert.equal(run('data.settings.owner'),'Restaurado');assert.equal(run('data.tpv.sales.length'),2);run('CAStore.validate(data)');a.dom.window.close();console.log('OK 1–11 integración: informes, edición, cero IRPF, catálogo, stock, devolución dañada, cobro manual, agenda repetida, resumen, copias y alcance de caja');})().catch(e=>{console.error(e);process.exit(1)});
