const assert=require('assert/strict'),fs=require('fs'),h=require('./helpers/app-dom.cjs');
async function test(name,fn){const c=h();try{await fn(c);console.log('OK '+name)}finally{c.dom.window.close()}}
(async()=>{
await test('Año, fechas reales, identificadores y valores de formulario',({run,el})=>{
 run(`data=CAStore.empty();data.movements=[{id:1,date:'2026-10-09',type:'Ingreso',concept:'VENTA2026',total:10,vat:21,paymentMethod:'cash'},{id:2,date:'2027-10-09',type:'Ingreso',concept:'VENTA2027',total:20,vat:21,paymentMethod:'cash'}];year.value='2026';renderMonth(10);year.value='2027';year.onchange()`);
 assert.match(el('monthList').textContent,/VENTA2027/);assert.doesNotMatch(el('monthList').textContent,/VENTA2026/);
 const base=run('CAStore.empty()'),move={id:1,date:'2026-02-31',type:'Ingreso',concept:'X',total:10,vat:21};assert.throws(()=>run('CAStore.validate('+JSON.stringify({...base,movements:[move]})+')'));
 move.date='2026-10-09';assert.throws(()=>run('CAStore.validate('+JSON.stringify({...base,movements:[move,move]})+')'));
 assert.throws(()=>run('CAStore.validate('+JSON.stringify({...base,bank:[{id:1,date:move.date,amount:2},{id:1,date:move.date,amount:3}]})+')'));
 run('data=CAStore.empty();save()');el('bankAmount').value='12abc';el('bankDate').value='2026-10-09';run('addBank()');assert.equal(run('data.bank.length'),0);el('bankAmount').value='12,50';run('addBank()');assert.equal(run('data.bank[0].amount'),12.5);
 run('CATPVUI.resetProduct()');el('tpvProductName').value='Sin precio';run('CATPVUI.saveProduct()');assert.equal(run('data.tpv.products.length'),0);el('tpvPrice').value='0';run('CATPVUI.saveProduct()');assert.equal(run('data.tpv.products[0].price'),0);
 run(`data.receivables=[{id:'r',client:'Ana',concept:'Servicio',reference:'',date:'2026-10-09',due:'2026-10-10',total:10,vat:0,status:'pending'}];CAProBusiness.editDue('r')`);assert.equal(el('dueVat').value,'0');
});
await test('Fallo de almacenamiento revierte alta, borrado y calendario sin duplicar',({w,run,el})=>{
 run('data=CAStore.empty();save()');el('staffName').value='Ana';const set=w.Storage.prototype.setItem;w.Storage.prototype.setItem=function(){throw Error('Cuota llena')};assert.throws(()=>run('CAEmployees.saveEmployee()'));assert.equal(run('(data.employees||[]).length'),0);assert.equal(el('staffName').value,'Ana');w.Storage.prototype.setItem=set;run('CAEmployees.saveEmployee()');assert.equal(run('data.employees.length'),1);
 w.Storage.prototype.setItem=function(){throw Error('Cuota llena')};assert.throws(()=>run(`toggleDay('2026-10-09')`));assert.equal(run('data.nonworking.length'),0);w.Storage.prototype.setItem=set;
 run(`data.bank.push({id:7,date:'2026-10-09',amount:30});save()`);w.Storage.prototype.setItem=function(){throw Error('Cuota llena')};assert.throws(()=>run('deleteBank(7)'));assert.equal(run('data.bank.length'),1);w.Storage.prototype.setItem=set;
});
await test('Importación y cambio de cuenta limpian formularios y cancelan logo tardío',async({w,run,el})=>{
 el('dueClient').value='Cliente anterior';el('dueConcept').value='Anterior';el('staffId').value='old';el('staffName').value='Empleado anterior';const raw=run('CAStore.empty()');w.FileReader=class{readAsText(){this.result=JSON.stringify(raw);this.onload()}};w.importData({target:{files:[{}],value:''}});assert.equal(el('dueClient').value,'');assert.equal(el('staffName').value,'');assert.equal(el('staffId').value,'');
 let ready;w.URL.createObjectURL=()=>'blob:test';w.URL.revokeObjectURL=()=>{};w.Image=class{naturalWidth=20;naturalHeight=20;decode(){return new Promise(r=>ready=r)}};w.HTMLCanvasElement.prototype.getContext=()=>({fillRect(){},drawImage(){}});w.HTMLCanvasElement.prototype.toDataURL=()=> 'data:image/jpeg;base64,/9j/YQ==';run(`data=CAStore.open('A');save()`);const pending=w.CAProBusiness.logo({target:{files:[{type:'image/jpeg',size:100}],value:'logo'}});run(`data=CAStore.open('B');save();CABackups.resetSnapshot()`);ready();await pending;assert.equal(run('!!CAStore.read("B").data.settings.branding?.logo'),false);
});
await test('Servicio manual y guardado nunca se añaden ocultos',({run,el})=>{
 run(`data=CAStore.empty();CATPV.ensure(data).products.push({id:'s',name:'Manicura',category:'',kind:'service',price:1000,vat:21,tracked:false,stock:0,duration:30,archived:false});CAAgendaUI.toggleService('s',true);CAAgendaUI.serviceMode('manual')`);el('agendaServiceName').value='Pedicura';el('agendaDate').value='2026-10-12';run('CAAgendaUI.save()');assert.equal(run('data.tpv.appointments[0].services.length'),0);assert.equal(run('data.tpv.appointments[0].serviceName'),'Pedicura');
 run(`CAAgendaUI.serviceMode('manual')`);el('agendaServiceName').value='Oculto';run(`CAAgendaUI.serviceMode('saved');CAAgendaUI.toggleService('s',true)`);el('agendaTime').value='11:00';run('CAAgendaUI.save()');assert.equal(run('data.tpv.appointments[1].serviceName'),'');assert.equal(run('data.tpv.appointments[1].services.length'),1);
});
await test('WhatsApp con teléfono nuevo usa puente Android, mensaje y cancelación',({w,run,el})=>{
 run(`data=CAStore.empty();CAAgenda.save(data,{customerId:'',productIds:[],serviceName:'Manicura',date:'2026-10-12',time:'09:15',duration:45,status:'pending',notes:''});save();CAAppointmentCalendarUI.open();CAAppointmentCalendarUI.actions(data.tpv.appointments[0].id)`);let args;w.AndroidContacts={openWhatsApp:(...a)=>args=a};run('CAAppointmentCalendarUI.actionWhatsApp()');assert.equal(el('appointmentPhoneDialog').open,true);el('appointmentPhone').value='abc';run('CAAppointmentCalendarUI.submitPhone()');assert.equal(args,undefined);assert.equal(el('appointmentPhoneDialog').open,true);el('appointmentPhone').value='600 123 456';run('CAAppointmentCalendarUI.submitPhone()');assert.equal(args[0],'34600123456');assert.equal(args[1],'Desde nuestro negocio le recordamos que su cita es el día 12/10/2026 a las 09:15. Muchas gracias.');run("data.settings.owner='Salón Raúl';CAAppointmentCalendarUI.actionWhatsApp()");el('appointmentPhone').value='600123456';run('CAAppointmentCalendarUI.submitPhone()');assert.equal(args[1],'Desde Salón Raúl le recordamos que su cita es el día 12/10/2026 a las 09:15. Muchas gracias.');assert.equal(el('appointmentPhoneDialog').open,false);
 run('CAAppointmentCalendarUI.actionWhatsApp()');el('appointmentPhoneDialog').close();assert.equal(run('data.tpv.customers.length'),0);
});
await test('Sincronización conserva carrito y formularios, incluso durante una descarga',async({w,run,el})=>{
 w.firebase={initializeApp(){throw Error('transporte de prueba')}};run(fs.readFileSync('web/cloud.js','utf8'));
 run(`data=CAStore.open('sync-user');CATPV.ensure(data).products.push({id:'p',name:'Champú',category:'',kind:'product',price:1000,vat:21,tracked:false,stock:0,archived:false});save();CAStore.persist({...CAStore.envelope,dirty:false});CATPVUI.add('p');authReady=true;cloudUser={uid:'sync-user'};db={doc:()=>({get:async()=>({exists:true,data:()=>({revision:2,commitId:'remote',payload:JSON.stringify({...CAStore.envelope.data,settings:{owner:'Nube',irpf:20}})})})})}`);
 await run('syncCloud(true)');assert.match(el('tpvCart').textContent,/Champú/);assert.equal(run('data.settings.owner'),'');run('CATPVUI.resetSnapshot();CAFormState.clear("all")');await run('syncCloud(true)');assert.equal(run('data.settings.owner'),'Nube');
 el('staffName').value='Borrador';el('staffName').dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal(run('CAFormState.hasDraft()'),true);await run('syncCloud(true)');assert.equal(el('staffName').value,'Borrador');
 run('CAFormState.clear("all");lastRead=0');let release;w.releaseFetch=()=>new Promise(r=>release=r);run(`db={doc:()=>({get:async()=>{await releaseFetch();return {exists:true,data:()=>({revision:3,commitId:'later',payload:JSON.stringify({...CAStore.envelope.data,settings:{owner:'Posterior',irpf:20}})})}}})}`);const sync=run('syncCloud(true)');el('staffName').dispatchEvent(new w.Event('input',{bubbles:true}));release();await sync;assert.equal(run('data.settings.owner'),'Nube');assert.equal(el('staffName').value,'Borrador');
});
const native=fs.readFileSync('app/src/main/java/com/miscuentas/pro/MainActivity.java','utf8');assert.match(native,/new ContactBridge\(\), "AndroidContacts"/);assert.match(native,/appendQueryParameter\("text", message\)/);assert.match(native,/params.getAcceptTypes\(\)/);assert.match(native,/images \? "image\/\*"/);assert.match(fs.readFileSync('app/src/main/AndroidManifest.xml','utf8'),/configChanges="orientation\|screenSize\|keyboardHidden"/);console.log('OK contratos Android: enlace con mensaje, selector de imágenes y rotación conserva WebView');
})().catch(e=>{console.error(e);process.exit(1)});
