const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),assets=path.join(root,'app/src/main/assets');
for(const name of fs.readdirSync(assets,{recursive:true}).filter(n=>fs.statSync(path.join(assets,n)).isFile())){assert.deepEqual(fs.readFileSync(path.join(assets,name)),fs.readFileSync(path.join(root,'web',name)),`Android/web difieren: ${name}`);if(name.endsWith('.js'))new vm.Script(fs.readFileSync(path.join(assets,name),'utf8'),{filename:name})}
const values=new Map(),ctx=vm.createContext({localStorage:{getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v)},structuredClone,crypto:require('node:crypto').webcrypto});for(const name of ['tpv-core.js','store.js'])vm.runInContext(fs.readFileSync(path.join(assets,name),'utf8'),ctx);
const sample={movements:[{id:1,date:'2026-01-04',type:'Ingreso',concept:'Venta',total:121,vat:21,accounting:242,withholding:7}],bank:[],nonworking:[],settings:{owner:'Empresa',irpf:20},gestIncome:{}};
values.set('mis_cuentas_pro_web_v1',JSON.stringify(sample));assert.equal(ctx.MCPStore.open(null).movements[0].accounting,242);assert.equal(ctx.MCPStore.key(null),'mcp_v2_guest');ctx.MCPStore.open('ana');ctx.MCPStore.save(sample);ctx.MCPStore.open('pepe');assert.equal(ctx.MCPStore.envelope.data.movements.length,0);ctx.MCPStore.open('ana');assert.equal(ctx.MCPStore.envelope.data.movements[0].accounting,242);assert.equal(ctx.MCPStore.envelope.data.movements[0].total,121);
const cloud=fs.readFileSync(path.join(assets,'cloud.js'),'utf8');assert.match(cloud,/projectId:'mis-cuentas-pro-b565d'/);assert.doesNotMatch(cloud,/projectId:.*control-autonomo/);
const gradle=fs.readFileSync(path.join(root,'app/build.gradle'),'utf8');assert.match(gradle,/applicationId 'com.miscuentas.pro'/);assert.match(gradle,/signingConfig signingConfigs.controlFixed/);
const java=fs.readFileSync(path.join(root,'app/src/main/java/com/miscuentas/pro/MainActivity.java'),'utf8');assert.match(java,/package com.miscuentas.pro/);assert.match(java,/mis_cuentas_pro_web_v1/);assert.match(java,/mcp_pin_hash/);
console.log('OK Sintaxis, Android/web, migración antigua, cuentas aisladas, Firebase y paquete MCP conservados');
