(function(root){'use strict';
const statuses=['pending','confirmed','completed','cancelled'],active=a=>['pending','confirmed'].includes(a.status),minutes=s=>/^([01]\d|2[0-3]):[0-5]\d$/.test(s)?Number(s.slice(0,2))*60+Number(s.slice(3)):NaN;
function ensure(d){const t=CATPV.ensure(d);return t.appointments??=[]}
function validateCalendar(c){if(!c||typeof c.enabled!=='boolean'||!Array.isArray(c.weekly)||c.weekly.length!==7||!Array.isArray(c.closedDates)||new Set(c.closedDates).size!==c.closedDates.length||c.closedDates.some(date=>!CATPV.validDate(date)))throw Error('Calendario laboral no válido');for(const intervals of c.weekly){if(!Array.isArray(intervals)||intervals.length>2)throw Error('Revisa los turnos de trabajo.');let end=-1;for(const r of intervals){if(!Number.isInteger(r.from)||!Number.isInteger(r.to)||r.from<0||r.to>1440||r.from>=r.to||r.from<end)throw Error('Revisa las horas de entrada y salida; los turnos no pueden solaparse.');end=r.to}}return c}
function calendarError(d,date,time,duration){if((d.nonworking||[]).includes(date))return 'El día está marcado como no trabajado en Movimientos.';const c=CATPV.ensure(d).workCalendar;if(!c?.enabled)return '';if(c.closedDates.includes(date))return 'El negocio está cerrado en esa fecha.';const weekday=new Date(date+'T12:00:00').getDay(),intervals=c.weekly[weekday]||[];if(!intervals.length)return 'Ese día de la semana está cerrado.';const start=minutes(time),end=start+Number(duration);return intervals.some(r=>start>=r.from&&end<=r.to)?'':'La cita completa debe quedar dentro de un turno del calendario laboral.'}
function setCalendar(d,c){validateCalendar(c);CATPV.ensure(d).workCalendar=structuredClone(c);return ensure(d).filter(a=>active(a)&&calendarError(d,a.date,a.time,a.duration))}
function filterServices(d,query='',category='*'){const normalize=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim(),q=normalize(query);return CATPV.ensure(d).products.filter(p=>p.kind==='service'&&!p.archived&&!p.temporary&&p.duration&&(category==='*'||String(p.category||'').trim()===category)&&normalize(p.name+' '+p.category).includes(q))}
function overlaps(d,date,time,duration,excludeId=''){const start=minutes(time),end=start+Number(duration);return ensure(d).filter(a=>a.id!==excludeId&&a.status!=='cancelled'&&a.date===date&&minutes(a.time)<end&&start<minutes(a.time)+a.duration)}
function slotError(d,date,time,duration,excludeId='',allowOccupied=false){const start=minutes(time),n=Number(duration);if(!CATPV.validDate(date)||!Number.isFinite(start)||!Number.isInteger(n)||n<1||start+n>1440)return 'Revisa la hora y duración.';const closed=calendarError(d,date,time,n);if(closed)return closed;return !allowOccupied&&overlaps(d,date,time,n,excludeId).length?'El hueco está ocupado o no cabe toda la duración de la cita.':''}
function weekDates(date){if(!CATPV.validDate(date))throw Error('Fecha no válida');const day=new Date(date+'T12:00:00');day.setDate(day.getDate()-(day.getDay()+6)%7);return Array.from({length:7},(_,i)=>{const next=new Date(day);next.setDate(next.getDate()+i);return next.getFullYear()+'-'+String(next.getMonth()+1).padStart(2,'0')+'-'+String(next.getDate()).padStart(2,'0')})}
function openRanges(d,dates){const c=CATPV.ensure(d).workCalendar;if(!c?.enabled)return [{from:0,to:1440}];const all=dates.flatMap(date=>(d.nonworking||[]).includes(date)||c.closedDates.includes(date)?[]:c.weekly[new Date(date+'T12:00:00').getDay()]).slice().sort((a,b)=>a.from-b.from),result=[];for(const r of all){const last=result[result.length-1];if(last&&r.from<=last.to)last.to=Math.max(last.to,r.to);else result.push({...r})}return result}
function serviceNames(a){return [...a.services.map(s=>s.name),...(a.serviceName?[a.serviceName]:[])]}
function validate(d){const appointments=ensure(d),ids=new Set(),t=CATPV.ensure(d);if(t.workCalendar!=null)validateCalendar(t.workCalendar);if(!Array.isArray(appointments))throw Error('Agenda no válida');for(const p of t.products)if(p.duration!=null&&(!Number.isInteger(p.duration)||p.duration<1||p.duration>1440))throw Error('Duración de servicio no válida');for(const a of appointments){if(typeof a.id!=='string'||!/^[-A-Za-z0-9_]{1,100}$/.test(a.id)||ids.has(a.id)||!CATPV.validDate(a.date)||!Number.isFinite(minutes(a.time))||!Number.isInteger(a.duration)||a.duration<1||minutes(a.time)+a.duration>1440||!statuses.includes(a.status)||typeof a.notes!=='string'||a.notes.length>500||typeof a.customerName!=='string'||(a.seriesId!=null&&(typeof a.seriesId!=='string'||!/^[-A-Za-z0-9_]{1,100}$/.test(a.seriesId)))||(a.serviceName!=null&&(typeof a.serviceName!=='string'||a.serviceName.length>120))||!Array.isArray(a.services)||a.services.some(s=>!t.products.some(p=>p.id===s.productId)||typeof s.name!=='string'||!Number.isInteger(s.duration)||s.duration<1)||(a.customerId&&!t.customers.some(c=>c.id===a.customerId))||(a.saleId&&!t.sales.some(s=>s.id===a.saleId&&s.appointmentId===a.id)))throw Error('Cita no válida');ids.add(a.id)}return d}
function save(d,input){const t=CATPV.ensure(d),list=ensure(d),old=list.find(a=>a.id===input.id);if(old?.saleId)throw Error('La cita ya tiene una venta; consúltala en TPV.');const customer=input.customerId?t.customers.find(c=>c.id===input.customerId&&(!c.archived||old?.customerId===c.id)):null;if(input.customerId&&!customer)throw Error('Selecciona un cliente activo.');const services=input.productIds.map(id=>{const historical=old?.services.find(s=>s.productId===id);const p=t.products.find(p=>p.id===id&&p.kind==='service'&&!p.archived);if(!p?.duration&&historical)return {...historical};if(!p?.duration)throw Error('Configura la duración del servicio en Catálogo.');return {productId:p.id,name:p.name,duration:p.duration}});if(!Array.isArray(input.productIds)||new Set(input.productIds).size!==input.productIds.length)throw Error('Revisa los servicios de la cita.');const a={id:old?.id||crypto.randomUUID(),customerId:input.customerId||'',customerName:customer?.name||'Cliente ocasional',date:input.date,time:input.time,duration:Number(input.duration),services,serviceName:(input.serviceName??old?.serviceName??'').trim(),notes:input.notes.trim(),status:input.status};if(a.status!=='cancelled'&&(!old||old.status==='cancelled'||old.date!==a.date||old.time!==a.time||old.duration!==a.duration)){const error=calendarError(d,a.date,a.time,a.duration);if(error)throw Error(error)}const candidate=structuredClone(d);ensure(candidate);candidate.tpv.appointments=list.filter(x=>x.id!==a.id).concat(a);validate(candidate);const conflicts=a.status==='cancelled'?[]:overlaps(d,a.date,a.time,a.duration,a.id);if(old)Object.assign(old,a);else list.push(a);return {appointment:a,conflicts}}
function repeatDates(date,frequency,count){if(!CATPV.validDate(date)||!['weekly','monthly'].includes(frequency)||!Number.isInteger(count)||count<2||count>(frequency==='weekly'?52:12))throw Error('Revisa la repetición: de 2 a 52 citas semanales o de 2 a 12 mensuales.');const base=new Date(date+'T12:00:00'),dates=[];for(let i=0;i<count;i++){let next;if(frequency==='weekly'){next=new Date(base);next.setDate(base.getDate()+7*i)}else{const year=base.getFullYear(),month=base.getMonth()+i,last=new Date(year,month+1,0).getDate();next=new Date(year,month,Math.min(base.getDate(),last),12)}dates.push(next.getFullYear()+'-'+String(next.getMonth()+1).padStart(2,'0')+'-'+String(next.getDate()).padStart(2,'0'))}return dates}
function saveRepeated(d,input,frequency,count){if(input.id)throw Error('La repetición se configura al crear una cita nueva.');const dates=repeatDates(input.date,frequency,count),next=structuredClone(d),seriesId=crypto.randomUUID(),results=[];for(const date of dates){try{const result=save(next,{...input,date});result.appointment.seriesId=seriesId;results.push(result)}catch(e){throw Error(date.split('-').reverse().join('/')+': '+e.message+' No se ha guardado ninguna cita de la serie.')}}CATPV.ensure(d).appointments=ensure(next);return {appointments:results.map(x=>x.appointment),conflicts:results.flatMap(x=>x.conflicts)}}
function end(a){const n=minutes(a.time)+a.duration;return String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0')}
function addCustomer(d,{name,phone='',email=''}){name=String(name).trim();phone=String(phone).trim();email=String(email).trim();if(!name||name.length>120||phone.length>60||email.length>160)throw Error('Revisa los datos del cliente.');const customer={id:crypto.randomUUID(),name,phone,email,notes:'',archived:false};CATPV.ensure(d).customers.push(customer);return customer}
function contactLinks(phone){const raw=String(phone??'').trim();if(!raw||!/^[+\d\s().-]+$/.test(raw)||raw.slice(1).includes('+'))return null;let digits=raw.replace(/\D/g,''),international=raw.startsWith('+')||raw.startsWith('00');if(raw.startsWith('00'))digits=digits.slice(2);if(digits.length<7||digits.length>15||(international&&digits.startsWith('0')))return null;return {call:'tel:'+(international?'+':'')+digits,whatsapp:international?'https://wa.me/'+digits:digits.length===9?'https://wa.me/34'+digits:null}}
function remove(d,id){const list=ensure(d),a=list.find(a=>a.id===id);if(!a)throw Error('La cita ya no existe.');for(const sale of CATPV.ensure(d).sales)if(sale.appointmentId===id)delete sale.appointmentId;CATPV.ensure(d).appointments=list.filter(a=>a.id!==id)}
function forCustomer(d,customerId,pendingOnly=false){if(!customerId)return [];return ensure(d).filter(a=>a.customerId===customerId&&(!pendingOnly||['pending','confirmed'].includes(a.status))).slice().sort((a,b)=>(a.date+' '+a.time).localeCompare(b.date+' '+b.time))}
root.CAAgenda={repeatDates,saveRepeated,overlaps,openRanges,serviceNames,slotError,weekDates,validateCalendar,calendarError,setCalendar,filterServices,forCustomer,ensure,validate,save,remove,end,minutes,addCustomer,contactLinks};
})(globalThis);
