(function(root){'use strict';let pending=null;
const key=uid=>'mcp_last_backup_'+(uid||'guest');
function summary(d){const t=d.tpv||{},dates=d.movements.map(m=>m.date).sort();return [d.movements.length+' ingresos y gastos',d.bank.length+' depósitos bancarios',(t.customers||[]).length+' clientes',(t.products||[]).filter(p=>!p.catalogueDeleted&&!p.temporary).length+' productos y servicios (incluye archivados)',(t.appointments||[]).length+' citas',(t.sales||[]).length+' ventas',(d.receivables||[]).filter(r=>r.status==='pending').length+' cobros pendientes', (d.receivables||[]).filter(r=>r.status==='paid').length+' registros ya cobrados',(d.employees||[]).length+' empleados',(d.vacations||[]).length+' vacaciones',dates.length?'Movimientos: '+dates[0]+' a '+dates.at(-1):'Sin movimientos'].join('\n')}
function refresh(){const el=document.getElementById('backupStatus');if(!el)return;try{const item=JSON.parse(localStorage.getItem(key(CAStore.uid))||'null');el.textContent=item?(item.confirmed?'Última copia guardada: ':'Última exportación iniciada: ')+new Date(item.at).toLocaleString('es-ES')+(item.confirmed?'':' · Comprueba que conservas el archivo descargado.'):'No hay fecha de copia registrada en este dispositivo para esta cuenta. Tus archivos de copias anteriores siguen siendo válidos.'}catch{el.textContent='Exporta una copia para guardar tus datos fuera de la app.'}}
function record(item,confirmed){try{localStorage.setItem(key(item.uid),JSON.stringify({at:confirmed?new Date().toISOString():item.at,confirmed}));refresh()}catch{alert('El archivo se ha preparado, pero no se pudo registrar la fecha de la copia.')}}
async function exportData(){if(pending)return alert('Termina o cancela el guardado de la copia anterior.');try{const item={uid:CAStore.uid,at:new Date().toISOString()},snapshot=CAStore.validate(data),stamp=item.at.replace(/[:.]/g,'-'),blob=new Blob([JSON.stringify(snapshot,null,2)],{type:'application/json'});item.name='Mis-Cuentas-PRO-copia-'+stamp+'.json';if(root.AndroidFiles){pending=item;document.getElementById('backupStatus').textContent='Elige dónde guardar la copia y confirma en Android.'}await downloadFileCompat(blob,item.name);if(!root.AndroidFiles)record(item,false)}catch(e){pending=null;alert('No se pudo exportar la copia: '+e.message)}}
function nativeSaved(ok,name){if(!pending||(name&&name!==pending.name))return;const item=pending;pending=null;if(ok)record(item,true);else refresh()}
function resetSnapshot(){CAStore.generation++;globalThis.CAFormState?.clear("all");document.querySelectorAll('dialog[open]').forEach(d=>d.close());root.CATPVUI?.resetSnapshot();root.CAAgendaUI?.reset();
 for(const id of ['staffId','staffName','paySalary','paySocial','payOther','payLink','vacStart','vacEnd','vacDays','dueId','dueClient','dueConcept','dueReference','dueTotal','movementEditId','concept','total','bankAmount','tpvDetailId','tpvPaymentId','tpvPaymentAction','manualSaleAccount','manualSaleName','manualSalePrice','stockAccount','stockProductId','stockQty','stockReason']){const e=document.getElementById(id);if(e)e.value=''}
 const values={staffYear:currentYear(),staffAllowance:0,staffBasis:'working',payDate:localToday(),vacStatus:'planned',dueVat:21,dueDate:localToday(),dueDeadline:localToday(),dueFilter:'pending',bankDate:localToday(),date:localToday(),tpvSaleDate:localToday(),tpvDue:localToday(),tpvClosingDate:localToday(),tpvOpening:0,tpvAdded:0,tpvWithdrawn:0,tpvCounted:0,tpvDiscount:0,tpvMethod:'cash',tpvPaymentMethod:'cash',owner:data.settings.owner,irpf:data.settings.irpf};for(const [id,value] of Object.entries(values)){const e=document.getElementById(id);if(e)e.value=value}
 root.CAProBusiness?.fillBrand?.();document.getElementById('monthList')?.removeAttribute('data-month');
}
function selectCopy(raw){
 if(raw&&typeof raw==='object'&&!Array.isArray(raw)&&!('movements' in raw)){
  const entries=Object.entries(raw);
  if(!entries.length||entries.some(([k])=>!k.startsWith('mcp_v2_backup_')))throw Error('Copia no válida');
  const copies=entries.map(([name,value])=>({name,data:CAStore.validate(value)})).sort((a,b)=>b.name.localeCompare(a.name));
  const labels=copies.map((c,i)=>{const stamp=c.name.match(/_(\d{13})_/);return (i+1)+'. '+(stamp?new Date(Number(stamp[1])).toLocaleString('es-ES'):c.name)+' · '+(c.data.settings.owner||'Sin nombre')+' · '+c.data.movements.length+' movimientos · '+(c.data.tpv?.appointments||[]).length+' citas'});
  const answer=prompt('Elige qué copia de recuperación quieres importar. Escribe su número:\n\n'+labels.join('\n'));
  if(answer===null)return null;
  if(!/^\d+$/.test(answer.trim()))throw Error('Número de copia no válido');
  const chosen=copies[Number(answer.trim())-1];if(!chosen)throw Error('Número de copia no válido');return chosen.data;
 }
 return CAStore.validate(raw);
}
function importData(e){const f=e.target.files?.[0];if(!f)return;const uid=CAStore.uid,reader=new FileReader();reader.onerror=()=>{e.target.value='';alert('No se pudo leer el archivo. Tus datos actuales se conservan.')};reader.onload=()=>{let committed=false;try{if(uid!==CAStore.uid)throw Error('La cuenta ha cambiado. Abre la copia de nuevo.');const imported=selectCopy(JSON.parse(reader.result));if(!imported)return;if(!confirm('Esta copia contiene:\n'+summary(imported)+'\n\n¿Sustituir los datos de esta cuenta por la copia? Se guardará una copia de recuperación y se descartarán los formularios y el carrito sin guardar.'))return;if(uid!==CAStore.uid)throw Error('La cuenta ha cambiado. Abre la copia de nuevo.');CAStore.backup(data,'antes_importar');CAStore.save(imported);committed=true;data=imported;resetSnapshot();owner.value=data.settings.owner;irpf.value=data.settings.irpf;render();if(root.scheduleSync)scheduleSync();alert('Copia importada')}catch(err){alert(committed?'La copia se ha guardado, pero no se pudo actualizar la pantalla: '+err.message+'. Cierra y abre la app.':'No se pudo importar: '+err.message+'. Tus datos actuales se conservan.')}finally{e.target.value=''}};reader.readAsText(f)}
function mount(){root.exportData=exportData;root.importData=importData;const old=root.render;root.render=function(...args){const result=old.apply(this,args);refresh();return result};refresh()}
root.CABackups={resetSnapshot,summary,refresh,nativeSaved};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})(globalThis);
