/* Costs are stored once as linked movements; employee details travel in the same backup. */
(function(){'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>crypto.randomUUID(),num=id=>Number($(id).value.replace(',','.')),list=()=>data.employees||[],costs=()=>data.payrolls||[],leave=()=>data.vacations||[];
function ready(){data.employees??=[];data.payrolls??=[];data.vacations??=[];}
function total(p){return p.salary+p.social+p.other}
function vacationDays(v){return leave().filter(x=>x.employeeId===v.employeeId&&x.start.slice(0,4)===String(v.year))}
function costTotal(y,m){return data.movements.filter(x=>x.payrollId&&Number(x.date.slice(0,4))===y&&(m==null||Number(x.date.slice(5,7))===m)).reduce((n,x)=>n+x.total,0)}
function options(){return list().filter(e=>!e.archived).map(e=>`<option value="${esc(e.id)}">${esc(e.name)}</option>`).join('')}
function draw(){if(!$('staffList'))return;ready();const y=currentYear();$('staffList').innerHTML=list().map(e=>{const vs=vacationDays({employeeId:e.id,year:y}),taken=vs.filter(v=>v.status==='taken').reduce((n,v)=>n+v.days,0),planned=vs.filter(v=>v.status==='planned').reduce((n,v)=>n+v.days,0),available=e.quotas?.[y]??(e.year===y?e.allowance:0);return `<div class="staffRow"><b>${esc(e.name)}${e.archived?' · Archivado':''}</b><p class="small">${y}: ${available} días disponibles · ${taken} disfrutados · ${planned} previstos · ${available-taken-planned} sin asignar. Cómputo: ${e.basis==='working'?'laborables':'naturales'}.</p><button class="tiny" onclick="CAEmployees.edit('${e.id}')">Editar cupo / nombre</button><button class="tiny" onclick="CAEmployees.archive('${e.id}')">${e.archived?'Reactivar':'Archivar'}</button></div>`}).join('')||'<p>Añade tu primer empleado.</p>';
for(const id of ['payEmployee','vacEmployee']){const old=$(id).value;$(id).innerHTML=options();if([...$(id).options].some(o=>o.value===old))$(id).value=old}
$('payList').innerHTML=costs().slice().sort((a,b)=>b.date.localeCompare(a.date)).map(p=>`<div class="staffRow"><b>${esc(list().find(e=>e.id===p.employeeId)?.name)} · ${p.date}</b><p>Sueldo ${eur(p.salary)} · SS empresa ${eur(p.social)} · Otros ${eur(p.other)}<br><b>Total ${eur(total(p))}</b></p><button class="tiny" onclick="CAEmployees.removeCost('${p.id}')">Eliminar coste / desvincular</button></div>`).join('')||'<p>Sin costes registrados.</p>';
$('vacList').innerHTML=leave().slice().sort((a,b)=>a.start.localeCompare(b.start)).map(v=>`<div class="staffRow"><b>${esc(list().find(e=>e.id===v.employeeId)?.name)}</b><p>${v.start} → ${v.end} · ${v.days} días · ${v.status==='taken'?'Disfrutados':'Previstos'}</p><button class="tiny" onclick="CAEmployees.toggleVacation('${v.id}')">${v.status==='taken'?'Marcar previstos':'Marcar disfrutados'}</button><button class="tiny" onclick="CAEmployees.removeVacation('${v.id}')">Eliminar</button></div>`).join('')||'<p>Sin vacaciones registradas.</p>';
const old=$('payLink').value;$('payLink').innerHTML='<option value="">Crear un gasto nuevo</option>'+data.movements.filter(m=>m.type==='Gasto'&&!m.payrollId&&m.vat===0).map(m=>`<option value="${m.id}">${m.date} · ${esc(m.concept)} · ${eur(m.total)}</option>`).join('');$('payLink').value=old;
}
function saveEmployee(){ready();const name=$('staffName').value.trim(),allowance=num('staffAllowance'),year=num('staffYear');if(!name||!Number.isFinite(allowance)||allowance<0||!Number.isInteger(year)||year<1900||year>2200)return alert('Revisa nombre, año y días.');const old=list().find(e=>e.id===$('staffId').value);const values={name,allowance,year,basis:$('staffBasis').value};if(old){old.quotas={...(old.quotas||{[old.year]:old.allowance}),[year]:allowance};Object.assign(old,values)}else list().push({id:uid(),...values,quotas:{[year]:allowance},archived:false});save();window.CAFormState?.clear('staff');$('staffId').value='';$('staffName').value='';}
function addCost(){ready();const employeeId=$('payEmployee').value,date=$('payDate').value,salary=num('paySalary'),social=num('paySocial'),other=num('payOther'),sum=salary+social+other;if(!employeeId||!/^\d{4}-\d{2}-\d{2}$/.test(date)||![salary,social,other].every(n=>Number.isFinite(n)&&n>=0)||sum<=0)return alert('Selecciona empleado, fecha e importes válidos.');if(costs().some(p=>p.employeeId===employeeId&&p.date.slice(0,7)===date.slice(0,7))&&!confirm('Ya hay un coste para este empleado y mes. ¿Añadir otro coste adicional?'))return;const id=uid(),link=Number($('payLink').value);let m=link?data.movements.find(m=>m.id===link):null;if(link&&(!m||m.payrollId||m.type!=='Gasto'||m.vat!==0||Math.abs(m.total-sum)>0.011||m.date!==date))return alert('El gasto existente debe tener la misma fecha, importe total y 0 % IVA. Ajusta los campos o elige crear un gasto.');const linked=!!m;if(!m){let movementId=Date.now();while(data.movements.some(m=>m.id===movementId))movementId++;m={id:movementId,type:'Gasto',date,concept:'Personal: '+list().find(e=>e.id===employeeId).name,total:sum,vat:0,withholding:0,gestoria:false,category:'otros',irpfDeductible:true,vatDeductible:false};data.movements.push(m)}m.payrollId=id;costs().push({id,employeeId,date,salary,social,other,movementId:m.id,linked});save();window.CAFormState?.clear('pay');alert('Coste guardado e incluido una sola vez en Gastos e Informes.');}
function addVacation(){ready();const employeeId=$('vacEmployee').value,start=$('vacStart').value,end=$('vacEnd').value,days=num('vacDays'),e=list().find(e=>e.id===employeeId);if(!e||!start||!end||end<start||start.slice(0,4)!==end.slice(0,4)||!Number.isFinite(days)||days<=0)return alert('Revisa las fechas y días. Si cruza de año, registra un periodo por año.');if(e.quotas?.[Number(start.slice(0,4))]==null&&e.year!==Number(start.slice(0,4)))return alert('Configura primero el cupo del empleado para ese año.');if(leave().some(v=>v.employeeId===employeeId&&start<=v.end&&end>=v.start))return alert('Ese periodo se solapa con otras vacaciones.');const assigned=vacationDays({employeeId,year:Number(start.slice(0,4))}).reduce((n,v)=>n+v.days,0);if(assigned+days>(e.quotas?.[Number(start.slice(0,4))]??e.allowance)&&!confirm('El periodo supera el cupo disponible. ¿Guardarlo igualmente?'))return;leave().push({id:uid(),employeeId,start,end,days,status:$('vacStatus').value});save();window.CAFormState?.clear('vac');}
window.CAEmployees={costTotal,total,draw,saveEmployee,addCost,addVacation,
edit(id){const e=list().find(e=>e.id===id);$('staffId').value=id;$('staffName').value=e.name;$('staffAllowance').value=e.quotas?.[currentYear()]??(e.year===currentYear()?e.allowance:0);$('staffYear').value=currentYear();$('staffBasis').value=e.basis;$('staffForm').scrollIntoView()},archive(id){const e=list().find(e=>e.id===id);e.archived=!e.archived;save()},
removeCost(id){const p=costs().find(p=>p.id===id);if(!confirm(p.linked?'Se quitará el vínculo con Empleados; el gasto original se conserva.':'Se eliminarán este coste y su gasto asociado.'))return;if(p.linked){delete data.movements.find(m=>m.id===p.movementId).payrollId}else data.movements=data.movements.filter(m=>m.id!==p.movementId);data.payrolls=costs().filter(p=>p.id!==id);save()},toggleVacation(id){const v=leave().find(v=>v.id===id);v.status=v.status==='taken'?'planned':'taken';save()},removeVacation(id){if(confirm('¿Eliminar este periodo?')){data.vacations=leave().filter(v=>v.id!==id);save()}}};
function mount(){const page=document.createElement('div');page.id='employees';page.className='page';page.innerHTML=`<div class="top"><div class="title">Empleados · Pro</div></div><p class="small">Vista previa sin suscripción activa. Registro manual de costes y vacaciones; no genera nóminas.</p><div class="panel staffForm" id="staffForm"><h3>Empleado y cupo de vacaciones</h3><input id="staffId" type="hidden"><label>Nombre</label><input id="staffName" maxlength="100"><label>Año del cupo</label><input id="staffYear" type="number" value="${currentYear()}"><label>Días anuales disponibles</label><input id="staffAllowance" type="number" min="0" step="0.5" value="0"><label>Cómputo acordado</label><select id="staffBasis"><option value="working">Días laborables</option><option value="calendar">Días naturales</option></select><button class="primary" onclick="CAEmployees.saveEmployee()">Guardar empleado</button><p class="small">Indica el cupo y el cómputo que correspondan. Se conserva el cupo de cada año y los periodos históricos.</p><div id="staffList"></div></div><div class="panel staffForm"><h3>Costes de personal</h3><label>Empleado</label><select id="payEmployee"></select><label>Fecha de registro</label><input id="payDate" type="date" value="${dateForSelectedYear()}"><label>Sueldo bruto €</label><input id="paySalary" inputmode="decimal" value="0"><label>Seguridad Social a cargo de la empresa €</label><input id="paySocial" inputmode="decimal" value="0"><label>Otros costes €</label><input id="payOther" inputmode="decimal" value="0"><label>¿Está ya registrado en Gastos?</label><select id="payLink"></select><p class="small">Vincula un gasto existente con la misma fecha e importe y 0 % IVA para evitar duplicarlo. Sueldo bruto + SS empresa: no sumes otra vez las deducciones del trabajador. Si registraste los componentes por separado, conserva esos gastos y no crees aquí un coste nuevo que los repita.</p><button class="primary" onclick="CAEmployees.addCost()">Guardar coste</button><div id="payList"></div></div><div class="panel staffForm"><h3>Vacaciones</h3><label>Empleado</label><select id="vacEmployee"></select><label>Desde</label><input id="vacStart" type="date"><label>Hasta</label><input id="vacEnd" type="date"><label>Días que consume del cupo</label><input id="vacDays" type="number" min="0.5" step="0.5"><p class="small">Introduce los días según el cómputo del empleado, descontando descansos y festivos cuando corresponda. La app no calcula el calendario laboral. Las vacaciones no añaden un gasto extra al sueldo.</p><select id="vacStatus"><option value="planned">Previstas</option><option value="taken">Disfrutadas</option></select><button class="primary" onclick="CAEmployees.addVacation()">Guardar vacaciones</button><div id="vacList"></div></div>`;document.querySelector('main')?.append(page)||$('home').parentElement.append(page);
document.querySelectorAll('.page:not(#home)').forEach(p=>{const b=document.createElement('button');b.className='secondary returnHome';b.textContent='← Volver a Inicio';b.onclick=()=>{show('home');window.scrollTo(0,0)};p.prepend(b)});
const originalRender=window.render;window.render=function(){originalRender();draw()};const originalBenefits=window.renderBenefits;window.renderBenefits=function(){originalBenefits();const n=costTotal(currentYear(),Number(benefitMonth.value));$('benefits').insertAdjacentHTML('afterbegin',`<p class="small">Costes de empleados incluidos en Gastos: <b>${eur(n)}</b>. Ya descontados del beneficio.</p>`)};draw();renderBenefits();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();
