(function(root){'use strict';
const key='mcp-preview-plan-1',free=()=>localStorage.getItem(key)==='free';
function notice(){alert('Esta función pertenece a Pro. Puedes volver a la vista previa completa desde Mi cuenta. No hay pagos activados.');return false}
function wrap(obj,names){if(!obj)return;for(const name of names){if(typeof obj[name]!=='function')continue;const original=obj[name];obj[name]=function(...args){if(free())return notice();return original.apply(this,args)}}}
function mount(){const menu=document.querySelector('#home>.homeMenu');for(const label of ['TPV','Informes','Agenda · Pro','Movimientos']){const tile=[...menu.children].find(x=>x.textContent.trim().endsWith(label));if(tile)menu.prepend(tile)}for(const label of ['Mi cuenta','Ajustes']){const tile=[...menu.children].find(x=>x.textContent.trim().endsWith(label));if(tile)menu.append(tile)}
const panel=document.createElement('section');panel.className='panel';panel.id='planPanel';panel.innerHTML=`<h3>Gratis y Pro</h3><p class="planNotice" id="planStatus"></p><table class="planTable"><tr><th>Gratis</th><th>Pro añade</th></tr><tr><td>Ingresos y gastos<br>Efectivo, tarjeta y transferencia<br>Caja / Banco y beneficio básico<br>Copias y sincronización</td><td>Empleados y vacaciones<br>TPV y stock<br>Agenda de citas<br>Cobros pendientes<br>Comparativas y gráficos<br>Todos los PDF, impresión y Excel<br>Informes trimestrales y anuales<br>Informe completo con logo</td></tr></table><p>Vista de pruebas: no hay suscripción, cargos ni prueba de siete días activa. El acceso personal gratuito definitivo se configurará más adelante.</p><button class="secondary" id="planToggle"></button>`;document.getElementById('account').append(panel);
const update=()=>{document.getElementById('planStatus').textContent=free()?'Vista gratuita de pruebas. Tus datos anteriores se conservan.':'Vista previa Pro: todas las funciones disponibles sin pagar.';const b=document.getElementById('planToggle');b.textContent=free()?'Volver a vista previa Pro':'Probar vista gratuita';for(const el of document.querySelectorAll('[data-pro-create]')){el.disabled=free();el.title=free()?'Función Pro':''}for(const id of ['proGraph','proResults','quarters','annualPayments']){const el=document.getElementById(id);if(el)el.hidden=free()}};
document.getElementById('planToggle').onclick=()=>{localStorage.setItem(key,free()?'preview':'free');location.reload()};
// Simulación de interfaz. Nunca se usa como verificación de una compra.
wrap(root.CAWorkCalendarUI,['save']);wrap(root.CAAgendaUI,['save','sale','saveClient']);wrap(root.CATPVUI,['startAppointment']);wrap(root.CATPVUI,['checkout','saveProduct','saveCustomer','saveStock']);wrap(root.CAEmployees,['saveEmployee','addCost','addVacation']);wrap(root.CAProBusiness,['saveReceivable','preview','pdf','excel','saveBrand','logo']);
for(const fn of ['CAWorkCalendarUI.save','CAAgendaUI.save','CAAgendaUI.saveClient','CAAgendaUI.sale','CATPVUI.startAppointment','CATPVUI.checkout','CATPVUI.saveProduct','CATPVUI.saveCustomer','CATPVUI.saveStock','CAEmployees.saveEmployee','CAEmployees.addCost','CAEmployees.addVacation','CAProBusiness.saveReceivable','CAProBusiness.preview','CAProBusiness.pdf','CAProBusiness.excel','CAProBusiness.saveBrand','CAProBusiness.logo'])for(const el of document.querySelectorAll('[onclick],[onchange]'))if((el.getAttribute('onclick')||el.getAttribute('onchange')||'').includes(fn))el.dataset.proCreate='true';
const compare=document.getElementById('proCompare');if(compare)compare.dataset.proCreate='true';for(const id of ['quarters','annualPayments']){const el=document.getElementById(id);if(!el)continue;const msg=document.createElement('p');msg.className='planNotice';msg.textContent='Informe Pro · Disponible en la vista previa completa.';msg.hidden=!free();el.before(msg)}
wrap(root,['viewMonthlyPDF','saveMonthlyPDF','downloadMonthlyPDF','printMonthlyReport','makeMonthlyPdfBytes']);wrap(root.CATPVUI,['exportSale']);
const download=root.downloadFileCompat;if(download)root.downloadFileCompat=function(blob,name,...args){if(free()&&/\.(pdf|xlsx)$/i.test(name||''))return notice();return download.call(this,blob,name,...args)};
for(const fn of ['viewMonthlyPDF','saveMonthlyPDF','downloadMonthlyPDF','printMonthlyReport','CATPVUI.exportSale'])for(const el of document.querySelectorAll('[onclick]'))if((el.getAttribute('onclick')||'').includes(fn))el.dataset.proCreate='true';
for(const el of document.querySelectorAll('[data-pro-create]'))if(!el.matches('input')&&!el.textContent.includes('Pro'))el.append(' · Pro');
update();const oldRender=root.render;root.render=function(...args){const result=oldRender.apply(this,args);update();return result};
root.CAPlans={isFree:free,refresh:update};
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})(globalThis);
