/* Lossless UTF-8 LZW with a reset marker; old JSON copies remain readable. */
(function(root){'use strict';const MAX_BYTES=16*1024*1024;
function hash(bytes){let n=2166136261;for(const x of bytes)n=Math.imul(n^x,16777619);return (n>>>0).toString(16)}
function compress(bytes){if(!bytes.length)return '';const codes=[],dict=new Map();let next=256,current=bytes[0];for(let i=1;i<bytes.length;i++){const byte=bytes[i],key=current*256+byte,found=dict.get(key);if(found!==undefined)current=found;else{codes.push(current);if(next<65535)dict.set(key,next++);else{codes.push(65535);dict.clear();next=256}current=byte}}codes.push(current);let result='';for(let i=0;i<codes.length;i+=8192){const chunk=[];for(const n of codes.slice(i,i+8192))chunk.push(n>>8,n&255);result+=String.fromCharCode(...chunk)}return btoa(result)}
function expand(encoded,expected){if(!Number.isSafeInteger(expected)||expected<1||expected>MAX_BYTES||typeof encoded!=='string'||encoded.length>MAX_BYTES*3||!/^[A-Za-z0-9+/]*={0,2}$/.test(encoded))throw Error('Copia comprimida no válida.');const raw=atob(encoded);if(raw.length%2)throw Error('Copia comprimida incompleta.');const output=new Uint8Array(expected),prefix=new Int32Array(65535),suffix=new Uint8Array(65535),stack=new Uint8Array(65536);let next=256,previous=-1,offset=0;
function unpack(code){let count=0;while(code>=256){if(code>=next||count>=65535)throw Error('Copia comprimida dañada.');stack[count++]=suffix[code];code=prefix[code]}stack[count++]=code;return count}
for(let i=0;i<raw.length;i+=2){const code=(raw.charCodeAt(i)<<8)|raw.charCodeAt(i+1);if(code===65535){if(previous<0)throw Error('Copia comprimida dañada.');next=256;previous=-1;continue}let count,first,special=false;if(code<next){count=unpack(code);first=stack[count-1]}else if(code===next&&previous>=0){count=unpack(previous);first=stack[count-1];special=true}else throw Error('Copia comprimida dañada.');if(offset+count+(special?1:0)>expected)throw Error('Copia comprimida demasiado grande.');while(count)output[offset++]=stack[--count];if(special)output[offset++]=first;if(previous>=0&&next<65535){prefix[next]=previous;suffix[next]=first;next++}previous=code}if(offset!==expected)throw Error('Copia comprimida incompleta.');return output}
function encode(d){const raw=JSON.stringify(d),bytes=new TextEncoder().encode(raw);if(bytes.length<=600000)return raw;if(bytes.length>MAX_BYTES)throw Error('La copia supera 16 MB. Exporta tus datos antes de continuar.');const packed=JSON.stringify({_caCodec:'lzw16-v1',bytes:bytes.length,checksum:hash(bytes),data:compress(bytes)});return new TextEncoder().encode(packed).length<bytes.length?packed:raw}
function decode(payload){if(typeof payload!=='string')throw Error('Copia de la nube no válida.');const value=JSON.parse(payload);if(value?._caCodec){if(value._caCodec!=='lzw16-v1')throw Error('Actualiza todos los dispositivos para abrir esta copia.');const bytes=expand(value.data,value.bytes);if(hash(bytes)!==value.checksum)throw Error('La copia comprimida no supera la comprobación de integridad.');return JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(bytes))}return value}
root.CASyncCodec={encode,decode};
})(globalThis);
